name: 'GitHub raw url'
description: 'Convert a normal GitHub url to its raw url'
inputs:
  github-url:  # id of input
    description: 'A normal GitHub url'
    required: true
    default: ''
  github-token:
    description: 'A github private token'
    required: false
    default: ''
outputs:
  raw-url: # id of output
    description: 'The raw url of a GitHub normal url'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: 'green'
